version: 2

models:
  - name: stg_crm__cust_info
    description: "Deduplicated and cleaned CRM customer records."
    columns:
      - name: cst_id
        tests:
          - not_null
          - unique
      - name: cst_firstname
        tests:
          - not_null
          - no_whitespace
      - name: cst_lastname
        tests:
          - not_null
          - no_whitespace
      - name: cst_marital_status
        tests:
          - accepted_values:
              config:
                severity: error
              arguments:
                values: ['Single', 'Married', 'n/a']
      - name: cst_gndr
        tests:
          - accepted_values:
              config:
                severity: error
              arguments:
                values: ['Male', 'Female', 'n/a']
      - name: cst_create_date
        tests:
          - not_null
      - name: dwh_create_date
        tests:
          - not_null
  - name: stg_crm__prd_info
    description: "Formatted CRM products records."
    columns:
      - name: prd_id
        tests:
          - not_null
          - unique
      - name: cat_id
        tests:
          - not_null
          - matches_pattern:
              arguments:
                pattern: '__[_]__'
      - name: prd_key
        tests:
          - not_null
      - name: prd_nm
        tests:
          - not_null
      - name: prd_cost
        tests:
          - not_null
      - name: prd_line
        tests:
          - accepted_values:
              config:
                severity: error
              arguments:
                values: ['Mountain', 'Road', 'Other Sales', 'Touring', 'n/a']
      - name: prd_start_dt
        tests:
          - not_null
          - assert_less_than:
              arguments:
                column_b: prd_end_dt
      - name: prd_end_dt
        tests:
          - not_null:
              config:
                severity: warn
      - name: dwh_create_date
        tests:
          - not_null
  - name: stg_crm__sales_details
    description: "Formatted CRM sales records."
    columns:
      - name: sls_ord_num
        tests:
          - not_null
          - no_whitespace
      - name: sls_prd_key
        tests:
          - not_null
          - no_whitespace
      - name: sls_cust_id
        tests:
          - not_null
          - dbt_utils.accepted_range:
              arguments:
                min_value: 0
                inclusive: false
      - name: sls_order_dt
        tests:
          - not_null:
              config:
                severity: warn
      - name: sls_ship_dt
        tests:
          - not_null
      - name: sls_due_dt
        tests:
          - not_null
      - name: sls_sales
        tests:
          - not_null
          - dbt_utils.accepted_range:
              arguments:
                min_value: 0
                inclusive: false
      - name: sls_quantity
        tests:
          - not_null
          - dbt_utils.accepted_range:
              arguments:
                min_value: 0
                inclusive: false
      - name: sls_price
        tests:
          - not_null
          - dbt_utils.accepted_range:
              arguments:
                min_value: 0
                inclusive: false
      - name: dwh_create_date
        tests:
          - not_null
  - name: stg_erp__loc_a101
    description: "Formatted ERP customer locations."
    columns:
      - name: cid
        tests:
          - not_null
          - unique
          - not_contains_string:
              arguments:
                text: '-'
      - name: cntry
        tests:
          - accepted_values:
              config:
                severity: error
              arguments:
                values: ['United States', 'Germany', 'Australia', 'Canada', 'France', 'United Kingdom', 'n/a']
      - name: dwh_create_date
        tests:
          - not_null
  - name: stg_erp__cust_az12
    description: "Formatted ERP customer birthday and gender records."
    columns:
      - name: cid
        tests:
          - not_null
          - unique
          - not_contains_string:
              arguments:
                text: 'NAS'
      - name: bdate
        tests:
          - not_null:
              config:
                severity: warn
      - name: gen
        tests:
          - accepted_values:
              config:
                severity: error
              arguments:
                values: ['Male', 'Female', 'n/a']
      - name: dwh_create_date
        tests:
          - not_null