-- Top Customer Concentration
-- Share of total revenue generated by the top 10% of customers by spending

WITH customer_revenue AS (
    SELECT
        customer_key
        ,SUM(total_sales_amount) AS customer_total
    FROM
        gold.fact_sales
    GROUP BY
        customer_key
),
ranked AS (
    SELECT
        customer_key
        ,customer_total
        ,NTILE(10) OVER (ORDER BY customer_total DESC) AS decile
    FROM
        customer_revenue
)

SELECT
    CAST(SUM(CASE WHEN decile = 1 THEN customer_total ELSE 0 END) AS DECIMAL(18,2)) 
    / SUM(customer_total) * 100 AS top10_concentration_pct
FROM
    ranked