# Dockerfile.corruption
# Purpose: Container for corrupt_bronze_sales.py. Delays sls_ship_dt of bronze.crm_sales_details.

FROM dwh-base:latest

WORKDIR /app

COPY scripts/requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

COPY scripts/bronze/corrupt_bronze_sales.py .

CMD ["python", "corrupt_bronze_sales.py"]