# ============================================================
#  Dockerfile.airflow
#  Purpose: Extends the base Airflow image with the Docker
#           provider package to enable DockerOperator in DAGs.
# ============================================================

FROM apache/airflow:2.9.1

RUN pip install apache-airflow-providers-docker==3.10.0 --constraint \
    "https://raw.githubusercontent.com/apache/airflow/constraints-2.9.1/constraints-3.11.txt"