version: 2

models:
  - name: dim_customer
    description: "Unified customer dimension combining CRM CSV and DummyJSON API sources."
    columns:
      - name: customer_key
        tests:
          - not_null
          - unique
          - dbt_utils.accepted_range:
              arguments:
                min_value: 0
                inclusive: false
      - name: customer_id
        tests:
          - not_null
          - unique
          - no_whitespace
      - name: customer_number
        tests:
          - not_null
          - unique:
              config:
                severity: warn    # n/a records can be detected with this.
          - no_whitespace
      - name: first_name
        tests:
          - not_null
          - no_whitespace
      - name: last_name
        tests:
          - not_null
          - no_whitespace
      - name: marital_status
        tests:
          - accepted_values:
              config:
                severity: error
              arguments:
                values: ['Single', 'Married', 'n/a']
      - name: gender
        tests:
          - accepted_values:
              config:
                severity: error
              arguments:
                values: ['Male', 'Female', 'n/a']
      - name: birthdate
        tests:
          - dbt_utils.accepted_range:   # Checks if birthday is between 1900-01-01 AND 18 years ago.
              arguments:
                min_value: "'1900-01-01'"
                max_value: "DATEADD(YEAR, -18, GETDATE())"
                inclusive: true
      - name: create_date
        tests:
          - dbt_utils.accepted_range:
              arguments:
                min_value: "'1900-01-01'"
                max_value: "GETDATE()"
                inclusive: true
      - name: data_source
        tests:
          - accepted_values:
              config:
                severity: error
              arguments:
                values: ['crm-csv','dummyjson-api']