version: 2

models:
  - name: dim_customers
    description: "Unified customer dimension combining CRM CSV and DummyJSON API sources."
    columns:
      - name: customer_key
        tests:
          - not_null
          - unique
          - dbt_utils.accepted_range:
              arguments:
                min_value: 0
                inclusive: false
      - name: customer_id
        tests:
          - not_null
          - unique
          - no_whitespace
      - name: customer_number
        tests:
          - not_null
          - unique:
              config:
                severity: warn    # n/a records can be detected with this.
          - no_whitespace
      - name: first_name
        tests:
          - not_null
          - no_whitespace
      - name: last_name
        tests:
          - not_null
          - no_whitespace
      - name: country
        tests:
          - accepted_values:
              config:
                severity: error
              arguments:
                values: ['United States', 'Germany', 'Australia', 'Canada', 'France', 'United Kingdom', 'n/a']
      - name: marital_status
        tests:
          - accepted_values:
              config:
                severity: error
              arguments:
                values: ['Single', 'Married', 'n/a']
      - name: gender
        tests:
          - accepted_values:
              config:
                severity: error
              arguments:
                values: ['Male', 'Female', 'n/a']
      - name: birthdate
        tests:
          - dbt_utils.accepted_range:   # Checks if birthday is between 1900-01-01 AND 18 years ago.
              arguments:
                min_value: "'1900-01-01'"
                max_value: "DATEADD(YEAR, -18, GETDATE())"
                inclusive: true
      - name: create_date
        tests:
          - dbt_utils.accepted_range:
              arguments:
                min_value: "'1900-01-01'"
                max_value: "GETDATE()"
                inclusive: true
      - name: data_source
        tests:
          - accepted_values:
              config:
                severity: error
              arguments:
                values: ['crm-csv','dummyjson-api']
  - name: dim_products
    description: "Unified product dimension combining ERP CSV and DummyJSON API sources."
    columns:
      - name: product_key
        tests:
          - not_null
          - unique
          - dbt_utils.accepted_range:
              arguments:
                min_value: 0
                inclusive: false
      - name: product_id
        tests:
          - not_null
          - unique
          - no_whitespace
      - name: product_number
        tests:
          - not_null
          - unique
          - no_whitespace
          - contains_string:
              arguments:
                text: '-'
      - name: product_name
        tests:
          - not_null
          - unique:
              config:
                severity: warn
      - name: category_id
        tests:
          - not_null
          - assert_case:
              arguments:
                case: 'upper'
      - name: category
        tests:
          - not_null
          - assert_case:
              arguments:
                case: 'initcap'
      - name: subcategory
        tests:
          - not_null
          - assert_case:
              arguments:
                case: 'initcap'
      - name: maintenance
        tests:
          - accepted_values:
              config:
                severity: error
              arguments:
                values: ['Yes', 'No', 'n/a']
      - name: cost
        tests:
          - not_null
          - dbt_utils.accepted_range:
              arguments:
                min_value: 0
                inclusive: true
      - name: product_line
        tests:
          - accepted_values:
              config:
                severity: error
              arguments:
                values: ['Mountain','Other Sales','Road','Touring','n/a']
      - name: start_date
        tests:
          - dbt_utils.accepted_range:
              arguments:
                min_value: "'1900-01-01'"
                max_value: "GETDATE()"
                inclusive: true
      - name: data_source
        tests:
          - accepted_values:
              config:
                severity: error
              arguments:
                values: ['erp-csv','dummyjson-api']
  - name: fact_sales
    description: "Unified order fact combining product and customer dimensions and silver CRM sales and API order sources."
    columns:
      - name: order_key
        tests:
          - not_null
          - unique
          - dbt_utils.accepted_range:
              arguments:
                min_value: 0
                inclusive: false
      - name: order_number
        tests:
          - not_null
          - no_whitespace
      - name: product_key
        tests:
          - not_null
          - relationships:
              arguments:
                to: ref('dim_products')
                field: product_key
      - name: customer_key
        tests:
          - not_null
          - relationships:
              arguments:
                to: ref('dim_customers')
                field: customer_key
      - name: order_date
        tests:
          - not_null:
              config:
                severity: warn
          - dbt_utils.accepted_range:
              arguments:
                min_value: "'1900-01-01'"
                max_value: "GETDATE()"
                inclusive: true
      - name: shipping_date
        tests:
          - not_null:
              config:
                severity: warn
          - dbt_utils.accepted_range:
              arguments:
                min_value: "'1900-01-01'"
                inclusive: true
      - name: due_date
        tests:
          - not_null:
              config:
                severity: warn
          - dbt_utils.accepted_range:
              arguments:
                min_value: "'1900-01-01'"
                inclusive: true
      - name: total_sales_amount
        tests:
          - not_null
          - dbt_utils.accepted_range:
              arguments:
                min_value: 0
                inclusive: false
          - assert_formula:
              arguments:
                column_a: 'unit_price'
                column_b: 'quantity'
                op: 'multiply'
      - name: quantity
        tests:
          - not_null
          - dbt_utils.accepted_range:
              arguments:
                min_value: 0
                inclusive: false
      - name: unit_price
        tests:
          - not_null
          - dbt_utils.accepted_range:
              arguments:
                min_value: 0
                inclusive: false
      - name: data_source
        tests:
          - accepted_values:
              config:
                severity: error
              arguments:
                values: ['crm-csv','dummyjson-api']